trigger:
  - master
  - develop

pr:
  - master
  - develop

variables:
  BUILDCONFIGURATION: Release
  RestoreBuildProjects: "**/*.csproj"
  TestProjects: "/IntegrationTests/IntegrationTests.csproj"
  vmImageName: "ubuntu-latest"

stages:
  - stage: BuildAndTest
    displayName: Build and Test
    jobs:
      - job: Build
        displayName: Build and Run Tests
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: "dotnet workload install aspire"

          - task: DotNetCoreCLI@2
            displayName: Build Solution
            inputs:
              projects: $(RestoreBuildProjects)
              arguments: -c $(BUILDCONFIGURATION)

          - task: DotNetCoreCLI@2
            displayName: Run Tests with Coverage
            inputs:
              command: test
              projects: "$(TestProjects)"
              arguments: '--configuration $(BUILDCONFIGURATION) --settings coverage.runsettings --collect "XPlat Code Coverage"'

          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            inputs:
              testResultsFiles: "**/test_results.trx"
              testResultsFormat: "VSTest"
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: "Publish Code Coverage"
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
