pr:
  - master
  - develop

variables:
  BUILDCONFIGURATION: Release
  RestoreBuildProjects: "**/*.csproj"
  TestProjects: "/IntegrationTests/IntegrationTests.csproj"
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: Build
        displayName: Build and Test
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'

          - task: Bash@3
            inputs:
              targetType: "inline"
              script: "dotnet workload install aspire"

          - task: DotNetCoreCLI@2
            displayName: Build Solution
            inputs:
              projects: $(RestoreBuildProjects)
              arguments: -c $(BUILDCONFIGURATION)

          - task: DotNetCoreCLI@2
            displayName: Run Tests
            inputs:
              command: test
              projects: "$(TestProjects)"
              arguments: '--configuration $(BUILDCONFIGURATION) --logger "trx;LogFileName=test_results.trx"'

          - task: PublishTestResults@2
            displayName: "Publish Test Results"
            inputs:
              testResultsFiles: "**/test_results.trx"
              testResultsFormat: "VSTest"
              failTaskOnFailedTests: true

          - task: PublishCodeCoverageResults@2
            displayName: "Publish Code Coverage"
            inputs:
              summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"
