using MTAA_Backend.Domain.Entities.Messages;
using MTAA_Backend.Domain.Entities.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MTAA_Backend.Domain.Entities.Files
{
    /// <summary>
    /// Represents a generic file stored in the system, potentially associated with different types of messages.
    /// Inherits from <see cref="BaseEntity"/> for common entity properties like creation and update timestamps.
    /// </summary>
    public class MyFile : BaseEntity
    {
        /// <summary>
        /// Gets or sets the unique identifier for the file.
        /// A new GUID is generated by default upon instantiation.
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets the size of the file in bytes.
        /// </summary>
        public long Length { get; set; }

        /// <summary>
        /// Gets or sets the short, relative path to the file.
        /// </summary>
        public string ShortPath { get; set; }

        /// <summary>
        /// Gets or sets the full, absolute path to the file.
        /// </summary>
        public string FullPath { get; set; }

        /// <summary>
        /// Gets or sets the MIME type or extension of the file (e.g., "image/jpeg", "audio/mp3").
        /// </summary>
        public string FileType { get; set; }

        /// <summary>
        /// Gets or sets the original name of the file.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the navigation property to a <see cref="FileMessage"/> if this file is part of a file message.
        /// </summary>
        public FileMessage? FileMessage { get; set; }

        /// <summary>
        /// Gets or sets the foreign key to the associated <see cref="FileMessage"/>.
        /// Nullable, indicating the file might not be linked to a <see cref="FileMessage"/>.
        /// </summary>
        public Guid? FileMessageId { get; set; }

        /// <summary>
        /// Gets or sets the navigation property to a <see cref="VoiceMessage"/> if this file is a voice message.
        /// </summary>
        public VoiceMessage? VoiceMessage { get; set; }

        /// <summary>
        /// Gets or sets the foreign key to the associated <see cref="VoiceMessage"/>.
        /// Nullable, indicating the file might not be linked to a <see cref="VoiceMessage"/>.
        /// </summary>
        public Guid? VoiceMessageId { get; set; }

        /// <summary>
        /// Gets or sets the navigation property to a <see cref="GifMessage"/> if this file is a GIF message.
        /// </summary>
        public GifMessage? GifMessage { get; set; }

        /// <summary>
        /// Gets or sets the foreign key to the associated <see cref="GifMessage"/>.
        /// Nullable, indicating the file might not be linked to a <see cref="GifMessage"/>.
        /// </summary>
        public Guid? GifMessageId { get; set; }
    }
}
