using MTAA_Backend.Domain.Entities.Users;
using MTAA_Backend.Domain.Resources.Posts.RecommendationSystem;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MTAA_Backend.Domain.Entities.Posts.RecommendationSystem
{
    /// <summary>
    /// Represents a base class for different types of recommendation feeds.
    /// This entity defines common properties for a recommendation feed, such as its type,
    /// a weight indicating its importance, and a collection of recommended items.
    /// </summary>
    public class BaseRecommendationFeed
    {
        /// <summary>
        /// Gets or sets the unique identifier for the recommendation feed.
        /// A new GUID is generated by default upon instantiation.
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets the type of the recommendation feed (e.g., "FromFollowers", "GlobalPopularity", "FromPreferences").
        /// This enum helps categorize different recommendation algorithms or sources.
        /// </summary>
        public RecommendationFeedTypes Type { get; set; }

        /// <summary>
        /// Gets or sets the weight assigned to this recommendation feed.
        /// This value can be used to prioritize or combine results from different feed types.
        /// </summary>
        public double Weight { get; set; }

        /// <summary>
        /// Gets or sets the total count of recommendation items currently in this feed.
        /// Defaults to 0. This might be used for quick access to the feed size without loading all items.
        /// </summary>
        public int RecommendationItemsCount { get; set; } = 0;

        /// <summary>
        /// Gets or sets the collection of <see cref="RecommendationItem"/>s that are part of this feed.
        /// This represents the actual content (e.g., posts, users) recommended by this feed.
        /// Initialized as a new HashSet to ensure no null reference issues.
        /// </summary>
        public ICollection<RecommendationItem> RecommendationItems { get; set; } = new HashSet<RecommendationItem>();
    }
}
