using MTAA_Backend.Domain.DTOs.Notifications.Responses;
using MTAA_Backend.Domain.Interfaces;
using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;

namespace MTAA_Backend.Application.Services.Notifications
{
    // Generated by GPT
    public class SSEClientStorage : ISSEClientStorage
    {
        private readonly ConcurrentDictionary<string, List<HttpResponse>> _clients = new();

        public async Task RegisterAsync(string userId, HttpResponse response, CancellationToken cancellationToken)
        {
            response.Headers.Add("Content-Type", "text/event-stream");

            _clients.AddOrUpdate(userId,
                _ => new List<HttpResponse> { response },
                (_, list) => { list.Add(response); return list; });

            try
            {
                while (!cancellationToken.IsCancellationRequested)
                {
                    await Task.Delay(1000, cancellationToken);
                }
            }
            catch (TaskCanceledException) { }
            finally
            {
                if (_clients.TryGetValue(userId, out var list))
                {
                    list.Remove(response);
                }
            }
        }

        public async Task SendNotificationAsync(string userId, NotificationResponse notification)
        {
            if (!_clients.TryGetValue(userId, out var responses)) return;

            var json = JsonSerializer.Serialize(notification);
            var data = $"data: {json}\n\n";
            var bytes = Encoding.UTF8.GetBytes(data);

            foreach (var response in responses.ToList())
            {
                try
                {
                    await response.Body.WriteAsync(bytes, 0, bytes.Length);
                    await response.Body.FlushAsync();
                }
                catch
                {
                    responses.Remove(response);
                }
            }
        }
    }
}
