//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAA_Backend.Domain.Resources.Localization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTAA_Backend.Domain.Resources.Localization.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel with this identification name already exists.
        /// </summary>
        public static string ChannelAlreadyExist {
            get {
                return ResourceManager.GetString("ChannelAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel not found.
        /// </summary>
        public static string ChannelNotFound {
            get {
                return ResourceManager.GetString("ChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat already exist.
        /// </summary>
        public static string ChatAlreadyExist {
            get {
                return ResourceManager.GetString("ChatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email already exists.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Phone number are null.
        /// </summary>
        public static string EmailAndPhoneNumberNull {
            get {
                return ResourceManager.GetString("EmailAndPhoneNumberNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not verified.
        /// </summary>
        public static string EmailIsNotVerified {
            get {
                return ResourceManager.GetString("EmailIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found.
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group visibility type does not exist.
        /// </summary>
        public static string GroupVisibilityTypeDontExist {
            get {
                return ResourceManager.GetString("GroupVisibilityTypeDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image format not allowed.
        /// </summary>
        public static string ImageFormatNotAllowed {
            get {
                return ResourceManager.GetString("ImageFormatNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post not found.
        /// </summary>
        public static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset avatar not found.
        /// </summary>
        public static string PresetAvatarNotFound {
            get {
                return ResourceManager.GetString("PresetAvatarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session registration has expired.
        /// </summary>
        public static string SignUpSessionExpired {
            get {
                return ResourceManager.GetString("SignUpSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in the group.
        /// </summary>
        public static string UserAlreadyInGroup {
            get {
                return ResourceManager.GetString("UserAlreadyInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered or the email is incorrect.
        /// </summary>
        public static string UserBadEmail {
            get {
                return ResourceManager.GetString("UserBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string UserBadPassword {
            get {
                return ResourceManager.GetString("UserBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not registered or the phone number is incorrect.
        /// </summary>
        public static string UserBadPhoneNumber {
            get {
                return ResourceManager.GetString("UserBadPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating user.
        /// </summary>
        public static string UserCreationError {
            get {
                return ResourceManager.GetString("UserCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have rules.
        /// </summary>
        public static string UserDontHaveRules {
            get {
                return ResourceManager.GetString("UserDontHaveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group membership not found.
        /// </summary>
        public static string UserGroupMembershipNotFound {
            get {
                return ResourceManager.GetString("UserGroupMembershipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in the group.
        /// </summary>
        public static string UserNotInGroup {
            get {
                return ResourceManager.GetString("UserNotInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code has already been sent.
        /// </summary>
        public static string VerificationCodeAlreadySent {
            get {
                return ResourceManager.GetString("VerificationCodeAlreadySent", resourceCulture);
            }
        }
    }
}
