//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAA_Backend.Domain.Resources.Localization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesPatterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesPatterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MTAA_Backend.Domain.Resources.Localization.Errors.ErrorMessagesPatterns", typeof(ErrorMessagesPatterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelAlreadyExist.
        /// </summary>
        public static string ChannelAlreadyExist {
            get {
                return ResourceManager.GetString("ChannelAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelNotFound.
        /// </summary>
        public static string ChannelNotFound {
            get {
                return ResourceManager.GetString("ChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatAlreadyExist.
        /// </summary>
        public static string ChatAlreadyExist {
            get {
                return ResourceManager.GetString("ChatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatNotFound.
        /// </summary>
        public static string ChatNotFound {
            get {
                return ResourceManager.GetString("ChatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAlreadyExists.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAndPhoneNumberNull.
        /// </summary>
        public static string EmailAndPhoneNumberNull {
            get {
                return ResourceManager.GetString("EmailAndPhoneNumberNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailIsNotVerified.
        /// </summary>
        public static string EmailIsNotVerified {
            get {
                return ResourceManager.GetString("EmailIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupVisibilityTypeDontExist.
        /// </summary>
        public static string GroupVisibilityTypeDontExist {
            get {
                return ResourceManager.GetString("GroupVisibilityTypeDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageFormatNotAllowed.
        /// </summary>
        public static string ImageFormatNotAllowed {
            get {
                return ResourceManager.GetString("ImageFormatNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresetAvatarNotFound.
        /// </summary>
        public static string PresetAvatarNotFound {
            get {
                return ResourceManager.GetString("PresetAvatarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUpSessionExpired.
        /// </summary>
        public static string SignUpSessionExpired {
            get {
                return ResourceManager.GetString("SignUpSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBadEmail.
        /// </summary>
        public static string UserBadEmail {
            get {
                return ResourceManager.GetString("UserBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBadPassword.
        /// </summary>
        public static string UserBadPassword {
            get {
                return ResourceManager.GetString("UserBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBadPhoneNumber.
        /// </summary>
        public static string UserBadPhoneNumber {
            get {
                return ResourceManager.GetString("UserBadPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreationError.
        /// </summary>
        public static string UserCreationError {
            get {
                return ResourceManager.GetString("UserCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDontHaveRules.
        /// </summary>
        public static string UserDontHaveRules {
            get {
                return ResourceManager.GetString("UserDontHaveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotAuthorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerificationCodeAlreadySent.
        /// </summary>
        public static string VerificationCodeAlreadySent {
            get {
                return ResourceManager.GetString("VerificationCodeAlreadySent", resourceCulture);
            }
        }
    }
}
