on:
  push:
    branches:
    - master
    - develop
    - feature/*
env:
  BUILDCONFIGURATION: Release
  RestoreBuildProjects: '**/*.csproj'
  TestProjects: '**/*[Tt]ests/*.csproj'
  vmImageName: ubuntu-latest
jobs:
  Build_Stage_Build:
    name: Build
    runs-on: ${{ env.vmImageName }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x
    - run: dotnet workload install aspire
      shell: bash
    - name: Build
      run: dotnet ${{ env.RestoreBuildProjects }} -c ${{ env.BuildConfiguration }}
    - name: Test with coverage filtering
      run: dotnet test ${{ env.TestProjects }} --configuration ${{ env.BuildConfiguration }} --settings coverage.runsettings --collect "XPlat Code Coverage"