name: Tests CI Pipeline

on:
  push:
    branches:
      - master
      - release/*
      - develop
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET SDK 9.x
    - name: Set up .NET SDK 9.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    # Install Aspire workload for .NET 9 (if necessary)
    - name: Install Aspire workload
      run: dotnet workload install aspire

    # Restore dependencies for MTAA_Backend.API and IntegrationTests
    - name: Restore dependencies
      run: |
        dotnet restore MTAA_Backend/MTAA_Backend.API.csproj
        dotnet restore IntegrationTests/IntegrationTests.csproj

    # Build the MTAA_Backend.API project
    - name: Build API project
      run: |
        dotnet build MTAA_Backend/MTAA_Backend.API.csproj -c Release

    # Run integration tests with code coverage
    - name: Run Integration Tests
      run: |
        dotnet test IntegrationTests/IntegrationTests.csproj -c Release --collect "XPlat Code Coverage" --results-directory ./TestResults

    # Publish test results (optional, for CI insights)
    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ./TestResults/

    # Publish code coverage results
    - name: Publish code coverage results
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/**/coverage.cobertura.xml